on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: 182548
          private_key: ${{ secrets.HOMEBREW_RELEASER_PRIVATE_KEY }}
          repository: bitcomplete/homebrew-tap
      - uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      # Build and publish .zip archive for Cloud Function deploys.
      - run: go mod vendor
      - run: zip -r gcp-runbatch-${GITHUB_REF#refs/tags/}.zip LICENSE *.go startup.py vendor
      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: bitcomplete-oss-q2tc
          service_account_key: ${{ secrets.GCP_PUBLIC_BUCKET_WRITER_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - run: gsutil cp gcp-runbatch-${GITHUB_REF#refs/tags/}.zip gs://bitcomplete-oss-public/gcp-runbatch/function/
